# Strategic merge patch for MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: mpod-v1.kb.io
  matchConditions:
  - name: "korder-pod-filter"
    expression: |
      has(object.metadata.annotations) && (
        'korder.dev/ticket-request' in object.metadata.annotations
      )