# Strategic merge patch for ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: vpod-v1.kb.io
  matchConditions:
  - name: "korder-pod-filter"
    expression: |
      has(object.metadata.annotations) && (
        'korder.dev/ticket-request' in object.metadata.annotations
      )