apiVersion: core.korder.dev/v1alpha1
kind: DaemonOrder
metadata:
  labels:
    app.kubernetes.io/name: korder
    app.kubernetes.io/managed-by: kustomize
  name: daemonorder-sample
spec:
  selector:
    matchLabels:
      app: daemon-worker
  template:
    metadata:
      labels:
        app: daemon-worker
    spec:
      window:
        duration: "24h"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
      lifecycle:
        cleanupPolicy: Delete
        ttlSecondsAfterFinished: 3600