# 仿照DaemonSet
apiVersion: core.korder.dev/v1alpha1
kind: DaemonOrder
metadata:
  name: daemon-order-sample
spec:
  paused: false # optional, 暂停订单
  refreshPolicy: "Always|OnClaim|Never" # 更明确的刷新策略
  selector:
    matchLabels:
      app: "app-name"
    matchExpressions:
      - { key: env, operator: In, values: [dev] }
  template:
    metadata:
      labels:
        app: "app-name"
        env: "dev"
    spec:
      window:
        # optional, 可以指定，或者由 Order 控制器 填充
        startTime: "" # 开始时间，格式为 RFC3339，例如：2024-01-01T00:00:00Z
        duration: 3600s
      schedulerName: default-scheduler
      priorityClassName: "priority-class-name"
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
      nodeName: "node-1"
      nodeSelector:
        kubernetes.io/arch: amd64
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
          preferredDuringSchedulingIgnoredDuringExecution: []
        podAffinity: {}
        podAntiAffinity: {}
      tolerations:
        - key: "key1"
          operator: "Equal"
          value: "value1"
          effect: "NoSchedule"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app: "app-name"
              env: "dev"

status:
  currentNumberScheduled: 1
  numberMisscheduled: 1
  desiredNumberScheduled: 0
  numberReady: 0
  updatedNumberScheduled: 1
  numberAvailable: 1
  numberUnavailable: 0
  # Add observed state of the resource here.
  observedGeneration: 1
  collisionCount: 1
  conditions:
    - type: Ready
      status: "True"
