apiVersion: core.korder.dev/v1alpha1
kind: Order
metadata:
  name: order-sample
spec:
  paused: false # optional, 暂停订单
  # Enable DaemonSet mode - one ticket per eligible node
  daemonSet: true
  replicas: 1
  strategy:
    type: "OneTime|Scheduled|Recurring"  # 合并策略类型
    schedule: "0 0 * * *"  # 仅在Scheduled/Recurring时有效
    refreshPolicy: "Always|OnClaim|Never"  # 更明确的刷新策略
  selector:
    matchLabels:
      app: "app-name"
    matchExpressions:
    - {key: env, operator: In, values: [dev]}
  template:
    metadata:
      labels:
        app: "app-name"
        env: "dev"
    spec:
      # optional, 可以指定，或者由 Order 控制器 填充
      startTime: "" # 开始时间，格式为 RFC3339，例如：2024-01-01T00:00:00Z
      duration: 3600s
      schedulerName: default-scheduler
      priorityClassName: "priority-class-name"
      resources:
        cpu: 100m
        memory: 500Mi
      nodeName: "node-1"
      nodeSelector:
        kubernetes.io/arch: amd64
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
          preferredDuringSchedulingIgnoredDuringExecution: []
        podAffinity: {}
        podAntiAffinity: {}
      tolerations:
        - key: "key1"
          operator: "Equal"
          value: "value1"
          effect: "NoSchedule"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app: "app-name"
              env: "dev"

status:
  replicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  terminalReplicas: 0
  updatedReplicas: 1
  # Add observed state of the resource here.
  observedGeneration: 1
  collisionCount: 1
  conditions:
  - type: Ready
    status: "True"
